server:
  port: ${dev.eureka.server.port}

spring:
  redis:
    host: 47.102.115.83
    port: 8888
    timeout: 20000
    fail-fast: true
###ThymeLeaf配置
#  thymeleaf:
#    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
#    mode: HTML5
#    #编码 可不用配置
#    encoding: UTF-8
#    #内容类别,可不用配置
#    content-type: text/html
#    #开发配置为false,避免修改模板还要重启服务器
#    cache: false
#    #配置模板路径，默认是templates，可以不用配置
#    prefix: classpath:/templates

